Junit testing
wolox-training/ss-java pull request #10
Opened 2020-11-26 21:24 UTC by SsopoWolox

Summary

Completed test controller class creation
Completed test repository class creation
Completed build module training
Completed run module training
Completed versioning project for this version

Trello Card
https://trello.com/c/u2KO3H3a/28-junit-testing

2020-11-26 21:52 UTC, jeymarsonwolox requested changes

2020-11-26 21:52 UTC, jeymarsonwolox commented on src/main/java/wolox/training/models/Book.java
> +    }
don't need two constructors, remove one and send `users = null` when you don't need this

2020-11-26 21:52 UTC, jeymarsonwolox commented on src/test/java/wolox/training/commons/Utils.java
> +    public static String asJsonString(final Object obj) {
great!!

2020-11-26 21:52 UTC, jeymarsonwolox commented on src/test/java/wolox/training/controllers/BookControllerTest.java
> +                        "{\"id\":1,\"genre\":\"Terror\",\"author\":\"Stephen King\",\"image\":\"image2.pgn\",\"title\":\"It\",\"subtitle\":\"-\",\"publisher\":\"Viking Press\",\"year\":\"1986\",\"pag
extract json to a constant

2020-11-26 21:52 UTC, jeymarsonwolox commented on src/test/java/wolox/training/repositories/UserRepositoryTest.java
> +        mockBook.setYear("1986");
you are repeating this many times, extract to a new class eg `BookFactory`

2020-11-30 19:18 UTC, jeymarsonwolox submitted a review, later dismissed

2020-11-30 19:35 UTC, martinremis requested changes

2020-11-30 19:35 UTC, martinremis commented on src/test/java/wolox/training/repositories/BookRepositoryTest.java
> +        org.assertj.core.api.Assertions.assertThat(BookFactory.getBook().getAuthor()).isNotNull();
Agrega esto como import para no tener que escribir todo el path del método.

2020-11-30 19:36 UTC, martinremis commented on src/test/java/wolox/training/repositories/BookRepositoryTest.java
> +        org.assertj.core.api.Assertions.assertThat(BookFactory.getBook().getAuthor()).isNotNull();
En todos los tests en donde tengas `org.assertj.core.api.Assertions.assertThat(`

2020-11-30 20:33 UTC, martinremis approved these changes

2020-11-30 20:42 UTC, jeymarsonwolox approved these changes

2020-11-30 20:48 UTC, merged