A method is created in userController to obtain the logged userName
wolox-training/ss-java pull request #13
Opened 2020-12-01 16:49 UTC by SsopoWolox

Summary

Completed created method for get userName to user logged
Completed run module training
Completed versioning project for this version

Trello Card
https://trello.com/c/v8ltdK52/27-acceder-a-la-informaci%C3%B3n-del-user-logueado

2020-12-01 17:05 UTC, jeymarsonwolox submitted a review, later dismissed
Excellent!!

2020-12-01 17:41 UTC, martinremis requested changes

2020-12-01 17:41 UTC, martinremis commented on src/main/java/wolox/training/controllers/UserController.java
> +        return name.get().getUserName();
You should check if there is a User object or not, even if it looks like there will always be.

2020-12-02 14:19 UTC, martinremis approved these changes

2020-12-02 14:32 UTC, jeymarsonwolox approved these changes

2020-12-02 14:34 UTC, merged