Create new class for Book model
wolox-training/ss-java pull request #2
Opened 2020-11-19 19:14 UTC by SsopoWolox

Summary

Completed the Book entity class creation
Completed the configuration of the annotation to scan entities
Completed build module training
Completed run module training
Completed versioning project for this version
Trello Card

https://trello.com/c/j2jnJ463/14-crear-modelo-de-book

2020-11-19 20:33 UTC, jeymarsonwolox requested changes

2020-11-19 20:33 UTC, jeymarsonwolox commented on src/main/java/Wolox/training/TrainingApplication.java
> +@EntityScan("Wolox.training.models")
This is not necessary, Spring Boot autoscan all component with annotations

2020-11-19 20:33 UTC, jeymarsonwolox commented on src/main/java/Wolox/training/models/Book.java
> +    public Book(Integer id, String genre, String author, String image, String title,
This is not necessary, JPA only need a empty constructor

2020-11-19 20:33 UTC, jeymarsonwolox commented on src/main/java/Wolox/training/models/Book.java
> +    @GeneratedValue(strategy = GenerationType.AUTO)
We use SEQUENCE instead of AUTO, because postgre we use AUTO creates a single autoincremental id for all tables

2020-11-19 20:33 UTC, jeymarsonwolox commented on src/main/java/Wolox/training/models/Book.java
> +    private String author;
add @NotNull to all  not nullable fields

2020-11-19 20:48 UTC, jeymarsonwolox requested changes

2020-11-19 20:48 UTC, jeymarsonwolox commented on src/main/java/Wolox/training/repositories/BookRepository.java
> +    @Query("SELECT b FROM Book b WHERE LOWER(b.author) = LOWER(:author)")
this is not necessary, you only need `Optional<Book> findByAuthor(String author);`
you can read more here https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#jpa.query-methods.query-creation

2020-11-19 23:34 UTC, jeymarsonwolox requested changes

2020-11-19 23:34 UTC, jeymarsonwolox commented on src/main/java/Wolox/training/TrainingApplication.java
> +@EnableJpaRepositories("Wolox.training.repositories")
this is not necessary

2020-11-19 23:34 UTC, jeymarsonwolox commented on src/main/java/Wolox/training/models/Book.java
> +        super();
`super();` is not necessary

2020-11-20 12:57 UTC, martinremis requested changes

2020-11-20 12:57 UTC, martinremis commented on src/main/java/Wolox/training/models/Book.java
> +    public void setId(Long id) {
You should not modify an auto-generated id.

2020-11-20 16:20 UTC, jeymarsonwolox approved these changes

2020-11-20 16:39 UTC, martinremis approved these changes

2020-11-20 18:36 UTC, merged